### ISSUE TITLE
Different URL format compared to `http` in `std`

### ISSUE THREAD

**Issue by timonson** [cmorten/native_http#3]
In `native_http` the `ctx.url` returns `http://0.0.0.0:8080/` where in the `std` library the value would be `/`. Is this intended behavior and why did you decide to do it this way?
Thanks!

**Comment by cmorten** [comment]
Hey @timonson 👋 

In std/http the authors opted to extract the url verbatim from the first line of the HTTP request, thus why you just have the path and to get the full url you would need to construct it using various other properties and headers.

REF: https://deno.land/std@0.102.0/http/_io.ts#L352

In this lib, the use of the use of `serveHttp` built into Deno yields a `RequestEvent` which contains the `url`. The Deno authors in this instance appear to have opted to provide the full url, and this lib just exposes that transparently. I suspect it was decided that a full url would be more useful than the path?

REF: https://deno.land/x/native_http@0.3.1/server.ts#L48

Happy to accept PRs to change this to try and match the old url style - because we expose the request as a getter, folks who want the full url could still find it easily. We just need to update the url getter to throw away the host, port, protocol etc.

**Comment by cmorten** [comment]
Also worth noting that looks like there are plans to introduce something similar to this lib directly into std/http so consider not investing too much time couple to this lib!

REF: https://github.com/denoland/deno_std/discussions/1034

**Comment by cmorten** [comment]
Going to close this for now as have answered the original question - if we want to make a change / feature request then can re-open or raise a new issue.
